stages:
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
    - src/preprocess.py
    outs:
    - data/processed/c1_BoW_Sentiment_Model.pkl
  train:
    cmd: python3 src/train.py
    deps:
    - src/train.py
    outs:
    - data/processed/c2_Classifier_Sentiment_Model
