stages:
  preprocess:
    cmd: python3 src/preprocess.py
    deps:
    - data/raw/restaurant_reviews_with_rating.tsv
    - src/preprocess.py
    - src/data/preprocess.py
    outs:
    - data/processed/c1_BoW_Sentiment_Model.pkl
    - data/processed/preprocessed_data_training
  train:
    cmd: python3 src/train.py
    deps:
    - data/raw/restaurant_reviews_with_rating.tsv
    - data/processed/preprocessed_data_training
    - src/train.py
    - src/models/train_model.py
    outs:
    - data/processed/c2_Classifier_Sentiment_Model
    metrics:
    - src/metrics.json:
        cache: false
