stages:
  get_data:
    cmd: python model_training/src/get_data.py
    deps:
    - model_training/src/get_data.py
    outs:
    - model_training/data/raw/restaurant_reviews_with_rating.tsv
  preprocess:
    cmd: python model_training/src/preprocess.py
    deps:
    - model_training/data/raw/restaurant_reviews_with_rating.tsv
    - model_training/src/preprocess.py
    - model_training/src/data/preprocess.py
    outs:
    - model_training/data/processed/c1_BoW_Sentiment_Model.pkl
    - model_training/data/processed/preprocessed_data_training
  train:
    cmd: python model_training/src/train.py
    deps:
    - model_training/data/raw/restaurant_reviews_with_rating.tsv
    - model_training/data/processed/preprocessed_data_training
    - model_training/src/train.py
    - model_training/src/models/train_model.py
    outs:
    - model_training/data/processed/c2_Classifier_Sentiment_Model
    metrics:
    - model_training/src/metrics.json:
        cache: false
