name: Code Quality
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install mllint
      - name: Lint with pylint
        run: pylint --fail-under=10.0 src/**/*.py
      - name: Run mllint
        run: |
          mllint -o report.md
      - name: Upload mllint report
        uses: actions/upload-artifact@v2
        with:
          name: mllint-report
          path: report.md
